apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: homeassistant
  name: homeassistant
  namespace: hass
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homeassistant
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: homeassistant
    spec:
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          name: homeassistant
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: homeassistant-claim0
            - mountPath: /etc/localtime
              name: homeassistant-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: homeassistant-claim0
          persistentVolumeClaim:
            claimName: homeassistant-claim0
        - name: homeassistant-claim1
          persistentVolumeClaim:
            claimName: homeassistant-claim1
            readOnly: true
status: {}